### ISSUE TITLE
A conflict with Webkul Marketplace: «Invalid method: Df\Config\A::options» on the backend customer screen 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/currency-format#4]
[https://mage2.pro/t/5700](https://mage2.pro/t/5700)

![26f6448cdc6da055f1eceded8b366bc2e4f41dac](https://user-images.githubusercontent.com/83204/46793133-ce854980-cd66-11e8-84bf-c8b1f5d568e8.png)

**Comment by dmitrii-fediuk** [comment]
Fixed in [1.1.2](https://github.com/mage2pro/currency-format/releases/tag/1.1.2).

**Comment by maarid** [comment]
Dmitry, you're exceptional.

Thank you,
