### ISSUE TITLE
What are the DF_**** Modules?

### ISSUE THREAD

**Issue by IbrahimS2** [mage2pro/currency-format#5]
What are the DF_**** Modules? Also the module is not working on Magento 2.2.6, It has been installed activated, and nothing happens on the frontend.

**Comment by dmitrii-fediuk** [comment]
Provide your website's URL.

**Comment by IbrahimS2** [comment]
@dmitry-fedyuk There is an NDA, but tell me your skype ID and I will go through it with you.

**Comment by dmitrii-fediuk** [comment]
The module is paid, not free, and I support the paid customers only.
