### ISSUE TITLE
«The store's database contains incorrect data for the ««Mage2.PRO» → «Currency» → «Format» → «» → «»» option. The data for this options are reset.»

### ISSUE THREAD

**Issue by VivekM296** [mage2pro/currency-format#8]
The store's database contains incorrect data for the ««Mage2.PRO» → «Currency» → «Format» → «» → «»» option.
The data for this options are reset.

This is what I'm getting after saving configuration, I know its paid but it should work in local, I'll purchase no issues, But its not working in local system also. 

See this https://prnt.sc/ryf0xk

For more specific I've 2 store views, english and arabic locale and I want for arabic locale that price separator ',' needs to be removed and use '.'

That's what I need ? is it fulfilled by this module ?

Do you have any idea ?

**Comment by dmitrii-fediuk** [comment]
You can hire me in Upwork: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)

**Comment by VivekM296** [comment]
Why you closed Man !? Just confirm that after purchase it'll work, I'll purchase now. @dmitry-fedyuk

**Comment by dmitrii-fediuk** [comment]
Fixed in `mage2pro/core` [7.0.6](https://github.com/mage2pro/core/releases/tag/7.0.6).
