### ISSUE TITLE
Error: Call to undefined method Df\Config\A::options() in mage2pro/currency-format/Plugin/Directory/Model/Currency.php:92

### ISSUE THREAD

**Issue by Kjellmann** [mage2pro/currency-format#9]
Testing the module in staging development and I've stumbled upon an issue when trying to edit or add new company customer from admin (Customers -> Companies).

Magento ver. 2.4.0

Full error:
`Error: Call to undefined method Df\Config\A::options() in /var/www/html/magentocloud/######/vendor/mage2pro/currency-format/Plugin/Directory/Model/Currency.php:92 Stack trace: #3 
/var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(135): Dfe\CurrencyFormat\Plugin\Directory\Model\Currency->aroundFormatTxt() #1 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Directory\Model\Currency\Interceptor->Magento\Framework\Interception\{closure}() #2 /var/www/html/magentocloud/######/generated/code/Magento/Directory/Model/Currency/Interceptor.php(169): Magento\Directory\Model\Currency\Interceptor->___callPlugins() #3 /var/www/html/magentocloud/######/vendor/magento/module-company-credit/Ui/Component/Form/AmountField.php(86): Magento\Directory\Model\Currency\Interceptor->formatTxt() #4 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Generator/UiComponent.php(164): Magento\CompanyCredit\Ui\Component\Form\AmountField->prepare() #5 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent() #6 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent() #7 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent() #8 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent() #9 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Generator/UiComponent.php(142): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent() #10 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Generator/UiComponent.php(103): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent() #11 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/GeneratorPool.php(81): Magento\Framework\View\Layout\Generator\UiComponent->process() #12 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout.php(352): Magento\Framework\View\Layout\GeneratorPool->process() #13 /var/www/html/magentocloud/######/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements() #14 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements() #15 /var/www/html/magentocloud/######/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks() #16 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks() #17 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout.php(259): Magento\Framework\View\Layout\Builder->build() #18 /var/www/html/magentocloud/######/vendor/magento/framework/View/Layout.php(884): Magento\Framework\View\Layout->build() #19 /var/www/html/magentocloud/######/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock() #20 /var/www/html/magentocloud/######/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout\Interceptor->getBlock() #21 /var/www/html/magentocloud/######/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu() #22 /var/www/html/magentocloud/######/vendor/magento/module-company/Controller/Adminhtml/Index/Edit.php(33): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() #23 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Company\Controller\Adminhtml\Index\Edit->execute() #24 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->___callParent() #25 /var/www/html/magentocloud/######/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->Magento\Framework\Interception\{closure}() #26 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() #27 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->Magento\Framework\Interception\{closure}() #28 /var/www/html/magentocloud/######/generated/code/Magento/Company/Controller/Adminhtml/Index/Edit/Interceptor.php(26): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->___callPlugins() #29 /var/www/html/magentocloud/######/vendor/magento/framework/App/Action/Action.php(111): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->execute() #30 /var/www/html/magentocloud/######/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch() #31 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch() #32 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->___callParent() #33 /var/www/html/magentocloud/######/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->Magento\Framework\Interception\{closure}() #34 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() #35 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->Magento\Framework\Interception\{closure}() #36 /var/www/html/magentocloud/######/generated/code/Magento/Company/Controller/Adminhtml/Index/Edit/Interceptor.php(39): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->___callPlugins() #37 /var/www/html/magentocloud/######/vendor/magento/framework/App/FrontController.php(186): Magento\Company\Controller\Adminhtml\Index\Edit\Interceptor->dispatch() #38 /var/www/html/magentocloud/######/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest() #39 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #40 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #41 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #42 /var/www/html/magentocloud/######/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #43 /var/www/html/magentocloud/######/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #44 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch() #45 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent() #46 /var/www/html/magentocloud/######/vendor/mage2pro/core/Framework/Plugin/App/Http.php(16): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() #47 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\App\Http->aroundLaunch() #48 /var/www/html/magentocloud/######/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() #49 /var/www/html/magentocloud/######/generated/code/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins() #50 /var/www/html/magentocloud/######/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #51 /var/www/html/magentocloud/######/pub/index.php(40): Magento\Framework\App\Bootstrap->run() #52 {main}`

**Comment by dmitrii-fediuk** [comment]
You use an outdated version of the https://github.com/mage2pro/core package.

**Comment by Kjellmann** [comment]
![2021-10-21_10-37](https://user-images.githubusercontent.com/16060012/138242069-9ce66bce-5561-4a93-b501-4406fc3bcc94.png)

Updated, but issue still occurs. Any ideas?

**Comment by dmitrii-fediuk** [comment]
Hire me in Upwork: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
